//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Relationship_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpEntities : DbContext
    {
        public EmpEntities()
            : base("name=EmpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AdminCustomer> AdminCustomers { get; set; }
        public virtual DbSet<AdminEmployee> AdminEmployees { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<PayRoll> PayRolls { get; set; }
        public virtual DbSet<query> queries { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Roletype> Roletypes { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<Signup> Signups { get; set; }
        public virtual DbSet<Signupcustomer> Signupcustomers { get; set; }
    }
}
