//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Relationship_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PayRoll
    {
        public int PayrollId { get; set; }
        [Required]
        public int Emp_Id { get; set; }
        [ForeignKey("Emp_Id")]
        [Required]
        public string ClassType { get; set; }
        [Required] 
        public int Totalsalary { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual salary salary { get; set; }
    }
}
