//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Relationship_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Request
    {
        [Required]
        public int Requestno { get; set; }
        [Required]
        public int custId { get; set; }
        [Required]
        public string custname { get; set; }
        [Required]
        public string custEmail { get; set; }
        [Required]
        public int EmpId { get; set; }
        [Required]
        public string subject { get; set; }
        [Required]
        public string message { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
