//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_Relationship_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Signupcustomer
    {
        [Required]
        public int id { get; set; }
        [Required]
        public int CustomerId { get; set; }
        [ForeignKey ("CustomerId")]
        [Required]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        public System.DateTime Createddate { get; set; }
        [Required]
        public string RoleName { get; set; }
    
        public virtual AdminCustomer AdminCustomer { get; set; }
    }
}
